name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REG }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -f .devcontainer/studio/Dockerfile -t autogen_studio-srv_img .
        docker tag autogen_studio-srv_img ${{ secrets.ACR_REG }}.azurecr.io/autogen_studio-srv_img
        docker push  ${{ secrets.ACR_REG }}.azurecr.io/autogen_studio-srv_img


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
        
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ vars.ACR_RESGRP }}
        dns-name-label: ${{ vars.ACR_RESGRP }}${{ github.run_number }}
        image: ${{ secrets.ACR_REG }}/sampleapp:${{ github.sha }}
        registry-login-server: ${{ secrets.ACR_REG }}
        registry-username: ${{ secrets.ACR_USERNAME }}
        registry-password: ${{ secrets.ACR_PASSWORD }}
        name: mcd79agstudio
        location: 'west europe'
  
